### ISSUE TITLE
Fix paths

### ISSUE THREAD

**Issue by emsi** [clear-code-projects/UltimatePygameIntro#8]
```pygame 2.1.2 (SDL 2.0.16, Python 3.10.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/emsi/PycharmProjects/UltimatePygameIntro/runner_class only.py", line 106, in <module>
    player.add(Player())
  File "/home/emsi/PycharmProjects/UltimatePygameIntro/runner_class only.py", line 8, in __init__
    player_walk_1 = pygame.image.load('graphics/player/player_walk_1.png').convert_alpha()
FileNotFoundError: No file 'graphics/player/player_walk_1.png' found in working director```
```
Clearly there is no `player` directory. It is `Player` .

**Comment by Bouzidi-Youssef** [comment]
you should change the file name `PLayer` to `player`
`Fly` to `fly` and both `Fly1.png` and `Fly2.png` to
`fly1.png` - `fly2.png`
